[project]
name = "dekapu-log-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "dotenv>=0.9.9",
    "influxdb-client>=1.49.0",
    "tenacity>=9.1.2",
    "tzdata>=2025.2",
]
